layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: rajat.sadh.75
  # hackerrank: your_username
  instagram: rajatsadh24
  # keybase: your_username
  linkedin: rs2402
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python Programming 
    web_url: https://github.com/topics/python
    image_url: http://www.trytoprogram.com/images/python_logo.png
    
  - name: Deep Learning
    web_url: https://github.com/topics/deep-learning
    image_url: https://www.doulos.com/images/logos/DeepLearning.jpg

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://4.bp.blogspot.com/-oyvo79YWqrM/XNaBhuXWzYI/AAAAAAAAABs/hqQRUbuTmqY4Tl5BfbCY6qqWAm27v68WQCLcBGAs/s1600/machine_learning_classification_graph.png
    
  - name: Raspberry Pi
    web_url: https://github.com/topics/raspberry-pi
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/raspberry-pi/raspberry-pi.png

theme: jekyll-theme-leap-day
